head_lower_tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_lower_tilt_joint
    joint_speed: 2.0
    motor:
        id: 4
        init: 512
        min: 0
        max: 4094
